version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: mkdir reports && mkdir reports/eslint
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: lint
          command: yarn lint:ci
          environment:
            ESLINT_REPORT: ./reports/eslint
          when: always
      - store_artifacts:
          path: reports
      - store_test_resutls:
          path: reports